version: "3" 
# Defines which compose version to use
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wp_sportsnerdnstg
      MYSQL_USER: sportsnerdnstg
      MYSQL_PASSWORD: ziUy_Z399TDCBWyfSNX1
    ports:
      - "3306:3306"
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: sportsnerdnstg
      WORDPRESS_DB_PASSWORD: ziUy_Z399TDCBWyfSNX1
      WORDPRESS_DB_NAME: wp_sportsnerdnstg
    volumes:
      ["./:/var/www/html"]
volumes:
  mysql: {}