name: Deploy to WP Engine
on:
  push:
    branches:
     - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: SFTP-Deploy-Action
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: sftp
        remote-host: wwwsnn.sftp.wpengine.com
        remote-user: wwwsnn-github
        remote-password: ${{ secrets.SFTP_PASSWORD }}
        remote-path: /
        remote-port: 2222